# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto_gen import lifecycle_pb2 as lifecycle__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lifecycle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagedDeviceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/controlsystem.lifecycle.ManagedDevice/Health',
                request_serializer=lifecycle__pb2.HealthRequest.SerializeToString,
                response_deserializer=lifecycle__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Capabilities = channel.unary_unary(
                '/controlsystem.lifecycle.ManagedDevice/Capabilities',
                request_serializer=lifecycle__pb2.Empty.SerializeToString,
                response_deserializer=lifecycle__pb2.Capabilities.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/controlsystem.lifecycle.ManagedDevice/Configure',
                request_serializer=lifecycle__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=lifecycle__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.Arm = channel.unary_unary(
                '/controlsystem.lifecycle.ManagedDevice/Arm',
                request_serializer=lifecycle__pb2.ArmRequest.SerializeToString,
                response_deserializer=lifecycle__pb2.ArmResponse.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/controlsystem.lifecycle.ManagedDevice/Start',
                request_serializer=lifecycle__pb2.StartRequest.SerializeToString,
                response_deserializer=lifecycle__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/controlsystem.lifecycle.ManagedDevice/Stop',
                request_serializer=lifecycle__pb2.StopRequest.SerializeToString,
                response_deserializer=lifecycle__pb2.StopResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_stream(
                '/controlsystem.lifecycle.ManagedDevice/Status',
                request_serializer=lifecycle__pb2.StatusRequest.SerializeToString,
                response_deserializer=lifecycle__pb2.StatusEvent.FromString,
                _registered_method=True)
        self.Disarm = channel.unary_unary(
                '/controlsystem.lifecycle.ManagedDevice/Disarm',
                request_serializer=lifecycle__pb2.DisarmRequest.SerializeToString,
                response_deserializer=lifecycle__pb2.DisarmResponse.FromString,
                _registered_method=True)


class ManagedDeviceServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Capabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Arm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disarm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagedDeviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=lifecycle__pb2.HealthRequest.FromString,
                    response_serializer=lifecycle__pb2.HealthResponse.SerializeToString,
            ),
            'Capabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.Capabilities,
                    request_deserializer=lifecycle__pb2.Empty.FromString,
                    response_serializer=lifecycle__pb2.Capabilities.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=lifecycle__pb2.ConfigureRequest.FromString,
                    response_serializer=lifecycle__pb2.ConfigureResponse.SerializeToString,
            ),
            'Arm': grpc.unary_unary_rpc_method_handler(
                    servicer.Arm,
                    request_deserializer=lifecycle__pb2.ArmRequest.FromString,
                    response_serializer=lifecycle__pb2.ArmResponse.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=lifecycle__pb2.StartRequest.FromString,
                    response_serializer=lifecycle__pb2.StartResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=lifecycle__pb2.StopRequest.FromString,
                    response_serializer=lifecycle__pb2.StopResponse.SerializeToString,
            ),
            'Status': grpc.unary_stream_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=lifecycle__pb2.StatusRequest.FromString,
                    response_serializer=lifecycle__pb2.StatusEvent.SerializeToString,
            ),
            'Disarm': grpc.unary_unary_rpc_method_handler(
                    servicer.Disarm,
                    request_deserializer=lifecycle__pb2.DisarmRequest.FromString,
                    response_serializer=lifecycle__pb2.DisarmResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controlsystem.lifecycle.ManagedDevice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('controlsystem.lifecycle.ManagedDevice', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagedDevice:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controlsystem.lifecycle.ManagedDevice/Health',
            lifecycle__pb2.HealthRequest.SerializeToString,
            lifecycle__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Capabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controlsystem.lifecycle.ManagedDevice/Capabilities',
            lifecycle__pb2.Empty.SerializeToString,
            lifecycle__pb2.Capabilities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controlsystem.lifecycle.ManagedDevice/Configure',
            lifecycle__pb2.ConfigureRequest.SerializeToString,
            lifecycle__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Arm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controlsystem.lifecycle.ManagedDevice/Arm',
            lifecycle__pb2.ArmRequest.SerializeToString,
            lifecycle__pb2.ArmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controlsystem.lifecycle.ManagedDevice/Start',
            lifecycle__pb2.StartRequest.SerializeToString,
            lifecycle__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controlsystem.lifecycle.ManagedDevice/Stop',
            lifecycle__pb2.StopRequest.SerializeToString,
            lifecycle__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/controlsystem.lifecycle.ManagedDevice/Status',
            lifecycle__pb2.StatusRequest.SerializeToString,
            lifecycle__pb2.StatusEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controlsystem.lifecycle.ManagedDevice/Disarm',
            lifecycle__pb2.DisarmRequest.SerializeToString,
            lifecycle__pb2.DisarmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
