# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: run_model.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'run_model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frun_model.proto\x12\x11\x63ontrolsystem.run\"\xc3\x01\n\nRunRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x15\n\rtemplate_name\x18\x02 \x01(\t\x12\x17\n\x0fparameters_json\x18\x03 \x01(\t\x12\x1c\n\x14required_calibration\x18\x04 \x03(\t\x12$\n\x17requested_descriptor_id\x18\x05 \x01(\x03H\x00\x88\x01\x01\x12\x17\n\x0fidempotency_key\x18\x06 \x01(\tB\x1a\n\x18_requested_descriptor_id\"\xa7\x01\n\x0b\x41\x63\x63\x65ptedJob\x12\x10\n\x08job_uuid\x18\x01 \x01(\t\x12.\n\x07request\x18\x02 \x01(\x0b\x32\x1d.controlsystem.run.RunRequest\x12\x15\n\rdescriptor_id\x18\x03 \x01(\x03\x12\x13\n\x0bsnapshot_id\x18\x04 \x01(\x03\x12\x14\n\x0csubmitted_at\x18\x05 \x01(\t\x12\x14\n\x0crequest_hash\x18\x06 \x01(\x0c\")\n\tRejection\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\x82\x01\n\x0f\x45nqueueResponse\x12\x32\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x0b\x32\x1e.controlsystem.run.AcceptedJobH\x00\x12\x30\n\x08rejected\x18\x02 \x01(\x0b\x32\x1c.controlsystem.run.RejectionH\x00\x42\t\n\x07outcome\"s\n\rCancelRequest\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x13\n\x0btarget_kind\x18\x02 \x01(\t\x12\x14\n\x0crequested_by\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x05 \x01(\t\":\n\x0e\x43\x61ncelResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05state\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\xd9\x01\n\nRunSummary\x12\x10\n\x08run_uuid\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nshot_count\x18\x03 \x01(\r\x12\x10\n\x08shots_ok\x18\x04 \x01(\r\x12\x12\n\nduration_s\x18\x05 \x01(\x01\x12\x13\n\x0bsnapshot_id\x18\x06 \x01(\x03\x12\x15\n\rdescriptor_id\x18\x07 \x01(\x03\x12\x1b\n\x13\x65xecution_bundle_id\x18\x08 \x01(\x03\x12\x17\n\x0f\x64urability_tier\x18\t \x01(\t\x12\r\n\x05notes\x18\n \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'run_model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNREQUEST']._serialized_start=39
  _globals['_RUNREQUEST']._serialized_end=234
  _globals['_ACCEPTEDJOB']._serialized_start=237
  _globals['_ACCEPTEDJOB']._serialized_end=404
  _globals['_REJECTION']._serialized_start=406
  _globals['_REJECTION']._serialized_end=447
  _globals['_ENQUEUERESPONSE']._serialized_start=450
  _globals['_ENQUEUERESPONSE']._serialized_end=580
  _globals['_CANCELREQUEST']._serialized_start=582
  _globals['_CANCELREQUEST']._serialized_end=697
  _globals['_CANCELRESPONSE']._serialized_start=699
  _globals['_CANCELRESPONSE']._serialized_end=757
  _globals['_RUNSUMMARY']._serialized_start=760
  _globals['_RUNSUMMARY']._serialized_end=977
# @@protoc_insertion_point(module_scope)
