# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto_gen import lifecycle_pb2 as lifecycle__pb2
from proto_gen import run_model_pb2 as run__model__pb2
from proto_gen import scheduler_pb2 as scheduler__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enqueue = channel.unary_unary(
                '/controlsystem.scheduler.Scheduler/Enqueue',
                request_serializer=run__model__pb2.RunRequest.SerializeToString,
                response_deserializer=run__model__pb2.EnqueueResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/controlsystem.scheduler.Scheduler/Cancel',
                request_serializer=run__model__pb2.CancelRequest.SerializeToString,
                response_deserializer=run__model__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_stream(
                '/controlsystem.scheduler.Scheduler/Status',
                request_serializer=lifecycle__pb2.StatusRequest.SerializeToString,
                response_deserializer=lifecycle__pb2.StatusEvent.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/controlsystem.scheduler.Scheduler/ListRuns',
                request_serializer=scheduler__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=scheduler__pb2.ListRunsResponse.FromString,
                _registered_method=True)


class SchedulerServicer:
    """Missing associated documentation comment in .proto file."""

    def Enqueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enqueue': grpc.unary_unary_rpc_method_handler(
                    servicer.Enqueue,
                    request_deserializer=run__model__pb2.RunRequest.FromString,
                    response_serializer=run__model__pb2.EnqueueResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=run__model__pb2.CancelRequest.FromString,
                    response_serializer=run__model__pb2.CancelResponse.SerializeToString,
            ),
            'Status': grpc.unary_stream_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=lifecycle__pb2.StatusRequest.FromString,
                    response_serializer=lifecycle__pb2.StatusEvent.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=scheduler__pb2.ListRunsRequest.FromString,
                    response_serializer=scheduler__pb2.ListRunsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controlsystem.scheduler.Scheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('controlsystem.scheduler.Scheduler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Scheduler:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Enqueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controlsystem.scheduler.Scheduler/Enqueue',
            run__model__pb2.RunRequest.SerializeToString,
            run__model__pb2.EnqueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controlsystem.scheduler.Scheduler/Cancel',
            run__model__pb2.CancelRequest.SerializeToString,
            run__model__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/controlsystem.scheduler.Scheduler/Status',
            lifecycle__pb2.StatusRequest.SerializeToString,
            lifecycle__pb2.StatusEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controlsystem.scheduler.Scheduler/ListRuns',
            scheduler__pb2.ListRunsRequest.SerializeToString,
            scheduler__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
