# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto_gen import run_model_pb2 as run__model__pb2
from proto_gen import lifecycle_pb2 as lifecycle__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\x17\x63ontrolsystem.scheduler\x1a\x0frun_model.proto\x1a\x0flifecycle.proto\" \n\x0fListRunsRequest\x12\r\n\x05limit\x18\x01 \x01(\r\"N\n\x06RunRow\x12\x10\n\x08run_uuid\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x15\n\rtemplate_name\x18\x03 \x01(\t\x12\x0c\n\x04user\x18\x04 \x01(\t\"A\n\x10ListRunsResponse\x12-\n\x04runs\x18\x01 \x03(\x0b\x32\x1f.controlsystem.scheduler.RunRow2\xe3\x02\n\tScheduler\x12L\n\x07\x45nqueue\x12\x1d.controlsystem.run.RunRequest\x1a\".controlsystem.run.EnqueueResponse\x12M\n\x06\x43\x61ncel\x12 .controlsystem.run.CancelRequest\x1a!.controlsystem.run.CancelResponse\x12X\n\x06Status\x12&.controlsystem.lifecycle.StatusRequest\x1a$.controlsystem.lifecycle.StatusEvent0\x01\x12_\n\x08ListRuns\x12(.controlsystem.scheduler.ListRunsRequest\x1a).controlsystem.scheduler.ListRunsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTRUNSREQUEST']._serialized_start=78
  _globals['_LISTRUNSREQUEST']._serialized_end=110
  _globals['_RUNROW']._serialized_start=112
  _globals['_RUNROW']._serialized_end=190
  _globals['_LISTRUNSRESPONSE']._serialized_start=192
  _globals['_LISTRUNSRESPONSE']._serialized_end=257
  _globals['_SCHEDULER']._serialized_start=260
  _globals['_SCHEDULER']._serialized_end=615
# @@protoc_insertion_point(module_scope)
